[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[env]
WASM_SERVER_RUNNER_ADDRESS = "0.0.0.0" 
WASM_SERVER_RUNNER_CUSTOM_INDEX_HTML = "./index.html"