create type "public"."checkbox" as enum ('None', 'Todo', 'Doing', 'Done');

drop function if exists "public"."add_block"(block jsonb);

drop function if exists "public"."add_task"(task_json jsonb);

drop function if exists "public"."add_time_allotment"(allotment_json jsonb);

drop function if exists "public"."get_tasks"();

create table "public"."block" (
    "uuid" uuid not null,
    "text" text not null default ''::text,
    "id" bigint generated by default as identity not null,
    "checkbox" checkbox not null default 'None'::checkbox
);


alter table "public"."block" enable row level security;

create table "public"."info" (
    "id" bigint generated by default as identity not null,
    "task_id" bigint not null,
    "block_id" bigint not null,
    "indent" smallint not null,
    "order" smallint not null
);


alter table "public"."info" enable row level security;

create table "public"."task" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "title_block_id" bigint not null,
    "allotment_id" bigint
);


alter table "public"."task" enable row level security;

create table "public"."test" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "test_col" text
);


alter table "public"."test" enable row level security;

create table "public"."time_allotment" (
    "seconds" bigint not null,
    "id" bigint generated by default as identity not null,
    "block_id" bigint not null
);


alter table "public"."time_allotment" enable row level security;

create table "public"."time_log" (
    "id" bigint generated by default as identity not null,
    "start" timestamp with time zone not null,
    "end" timestamp with time zone not null,
    "block_id" bigint not null
);


alter table "public"."time_log" enable row level security;

CREATE UNIQUE INDEX content_id_key ON public.block USING btree (id);

CREATE UNIQUE INDEX content_pkey ON public.block USING btree (id);

CREATE UNIQUE INDEX info_block_id_key ON public.info USING btree (block_id);

CREATE UNIQUE INDEX info_id_key ON public.info USING btree (id);

CREATE UNIQUE INDEX info_pkey ON public.info USING btree (id);

CREATE UNIQUE INDEX task_content_key ON public.task USING btree (title_block_id);

CREATE UNIQUE INDEX task_id_key ON public.task USING btree (id);

CREATE UNIQUE INDEX task_pkey ON public.task USING btree (id);

CREATE UNIQUE INDEX test_pkey ON public.test USING btree (id);

CREATE UNIQUE INDEX time_allotment_pkey ON public.time_allotment USING btree (id);

CREATE UNIQUE INDEX time_allotment_task_id_key ON public.time_allotment USING btree (id);

CREATE UNIQUE INDEX time_entry_id_key ON public.time_log USING btree (id);

CREATE UNIQUE INDEX time_entry_pkey ON public.time_log USING btree (id);

alter table "public"."block" add constraint "content_pkey" PRIMARY KEY using index "content_pkey";

alter table "public"."info" add constraint "info_pkey" PRIMARY KEY using index "info_pkey";

alter table "public"."task" add constraint "task_pkey" PRIMARY KEY using index "task_pkey";

alter table "public"."test" add constraint "test_pkey" PRIMARY KEY using index "test_pkey";

alter table "public"."time_allotment" add constraint "time_allotment_pkey" PRIMARY KEY using index "time_allotment_pkey";

alter table "public"."time_log" add constraint "time_entry_pkey" PRIMARY KEY using index "time_entry_pkey";

alter table "public"."block" add constraint "content_id_key" UNIQUE using index "content_id_key";

alter table "public"."info" add constraint "info_block_id_key" UNIQUE using index "info_block_id_key";

alter table "public"."info" add constraint "info_id_key" UNIQUE using index "info_id_key";

alter table "public"."info" add constraint "public_info_block_id_fkey" FOREIGN KEY (block_id) REFERENCES block(id) not valid;

alter table "public"."info" validate constraint "public_info_block_id_fkey";

alter table "public"."info" add constraint "public_info_task_id_fkey" FOREIGN KEY (task_id) REFERENCES task(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."info" validate constraint "public_info_task_id_fkey";

alter table "public"."task" add constraint "public_task_allotment_fkey" FOREIGN KEY (allotment_id) REFERENCES time_allotment(id) not valid;

alter table "public"."task" validate constraint "public_task_allotment_fkey";

alter table "public"."task" add constraint "public_task_title_id_fkey" FOREIGN KEY (title_block_id) REFERENCES block(id) not valid;

alter table "public"."task" validate constraint "public_task_title_id_fkey";

alter table "public"."task" add constraint "public_task_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."task" validate constraint "public_task_user_id_fkey";

alter table "public"."task" add constraint "task_content_key" UNIQUE using index "task_content_key";

alter table "public"."task" add constraint "task_id_key" UNIQUE using index "task_id_key";

alter table "public"."time_allotment" add constraint "public_time_allotment_block_id_fkey" FOREIGN KEY (block_id) REFERENCES block(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."time_allotment" validate constraint "public_time_allotment_block_id_fkey";

alter table "public"."time_allotment" add constraint "time_allotment_task_id_key" UNIQUE using index "time_allotment_task_id_key";

alter table "public"."time_log" add constraint "public_time_log_block_id_fkey" FOREIGN KEY (block_id) REFERENCES block(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."time_log" validate constraint "public_time_log_block_id_fkey";

alter table "public"."time_log" add constraint "time_entry_id_key" UNIQUE using index "time_entry_id_key";

grant delete on table "public"."block" to "anon";

grant insert on table "public"."block" to "anon";

grant references on table "public"."block" to "anon";

grant select on table "public"."block" to "anon";

grant trigger on table "public"."block" to "anon";

grant truncate on table "public"."block" to "anon";

grant update on table "public"."block" to "anon";

grant delete on table "public"."block" to "authenticated";

grant insert on table "public"."block" to "authenticated";

grant references on table "public"."block" to "authenticated";

grant select on table "public"."block" to "authenticated";

grant trigger on table "public"."block" to "authenticated";

grant truncate on table "public"."block" to "authenticated";

grant update on table "public"."block" to "authenticated";

grant delete on table "public"."block" to "service_role";

grant insert on table "public"."block" to "service_role";

grant references on table "public"."block" to "service_role";

grant select on table "public"."block" to "service_role";

grant trigger on table "public"."block" to "service_role";

grant truncate on table "public"."block" to "service_role";

grant update on table "public"."block" to "service_role";

grant delete on table "public"."info" to "anon";

grant insert on table "public"."info" to "anon";

grant references on table "public"."info" to "anon";

grant select on table "public"."info" to "anon";

grant trigger on table "public"."info" to "anon";

grant truncate on table "public"."info" to "anon";

grant update on table "public"."info" to "anon";

grant delete on table "public"."info" to "authenticated";

grant insert on table "public"."info" to "authenticated";

grant references on table "public"."info" to "authenticated";

grant select on table "public"."info" to "authenticated";

grant trigger on table "public"."info" to "authenticated";

grant truncate on table "public"."info" to "authenticated";

grant update on table "public"."info" to "authenticated";

grant delete on table "public"."info" to "service_role";

grant insert on table "public"."info" to "service_role";

grant references on table "public"."info" to "service_role";

grant select on table "public"."info" to "service_role";

grant trigger on table "public"."info" to "service_role";

grant truncate on table "public"."info" to "service_role";

grant update on table "public"."info" to "service_role";

grant delete on table "public"."task" to "anon";

grant insert on table "public"."task" to "anon";

grant references on table "public"."task" to "anon";

grant select on table "public"."task" to "anon";

grant trigger on table "public"."task" to "anon";

grant truncate on table "public"."task" to "anon";

grant update on table "public"."task" to "anon";

grant delete on table "public"."task" to "authenticated";

grant insert on table "public"."task" to "authenticated";

grant references on table "public"."task" to "authenticated";

grant select on table "public"."task" to "authenticated";

grant trigger on table "public"."task" to "authenticated";

grant truncate on table "public"."task" to "authenticated";

grant update on table "public"."task" to "authenticated";

grant delete on table "public"."task" to "service_role";

grant insert on table "public"."task" to "service_role";

grant references on table "public"."task" to "service_role";

grant select on table "public"."task" to "service_role";

grant trigger on table "public"."task" to "service_role";

grant truncate on table "public"."task" to "service_role";

grant update on table "public"."task" to "service_role";

grant delete on table "public"."test" to "anon";

grant insert on table "public"."test" to "anon";

grant references on table "public"."test" to "anon";

grant select on table "public"."test" to "anon";

grant trigger on table "public"."test" to "anon";

grant truncate on table "public"."test" to "anon";

grant update on table "public"."test" to "anon";

grant delete on table "public"."test" to "authenticated";

grant insert on table "public"."test" to "authenticated";

grant references on table "public"."test" to "authenticated";

grant select on table "public"."test" to "authenticated";

grant trigger on table "public"."test" to "authenticated";

grant truncate on table "public"."test" to "authenticated";

grant update on table "public"."test" to "authenticated";

grant delete on table "public"."test" to "service_role";

grant insert on table "public"."test" to "service_role";

grant references on table "public"."test" to "service_role";

grant select on table "public"."test" to "service_role";

grant trigger on table "public"."test" to "service_role";

grant truncate on table "public"."test" to "service_role";

grant update on table "public"."test" to "service_role";

grant delete on table "public"."time_allotment" to "anon";

grant insert on table "public"."time_allotment" to "anon";

grant references on table "public"."time_allotment" to "anon";

grant select on table "public"."time_allotment" to "anon";

grant trigger on table "public"."time_allotment" to "anon";

grant truncate on table "public"."time_allotment" to "anon";

grant update on table "public"."time_allotment" to "anon";

grant delete on table "public"."time_allotment" to "authenticated";

grant insert on table "public"."time_allotment" to "authenticated";

grant references on table "public"."time_allotment" to "authenticated";

grant select on table "public"."time_allotment" to "authenticated";

grant trigger on table "public"."time_allotment" to "authenticated";

grant truncate on table "public"."time_allotment" to "authenticated";

grant update on table "public"."time_allotment" to "authenticated";

grant delete on table "public"."time_allotment" to "service_role";

grant insert on table "public"."time_allotment" to "service_role";

grant references on table "public"."time_allotment" to "service_role";

grant select on table "public"."time_allotment" to "service_role";

grant trigger on table "public"."time_allotment" to "service_role";

grant truncate on table "public"."time_allotment" to "service_role";

grant update on table "public"."time_allotment" to "service_role";

grant delete on table "public"."time_log" to "anon";

grant insert on table "public"."time_log" to "anon";

grant references on table "public"."time_log" to "anon";

grant select on table "public"."time_log" to "anon";

grant trigger on table "public"."time_log" to "anon";

grant truncate on table "public"."time_log" to "anon";

grant update on table "public"."time_log" to "anon";

grant delete on table "public"."time_log" to "authenticated";

grant insert on table "public"."time_log" to "authenticated";

grant references on table "public"."time_log" to "authenticated";

grant select on table "public"."time_log" to "authenticated";

grant trigger on table "public"."time_log" to "authenticated";

grant truncate on table "public"."time_log" to "authenticated";

grant update on table "public"."time_log" to "authenticated";

grant delete on table "public"."time_log" to "service_role";

grant insert on table "public"."time_log" to "service_role";

grant references on table "public"."time_log" to "service_role";

grant select on table "public"."time_log" to "service_role";

grant trigger on table "public"."time_log" to "service_role";

grant truncate on table "public"."time_log" to "service_role";

grant update on table "public"."time_log" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."test"
as permissive
for insert
to authenticated
with check (true);


create policy "Read access for authenticated users only"
on "public"."test"
as permissive
for select
to authenticated
using (true);



