revoke delete on table "public"."time_log" from "anon";

revoke insert on table "public"."time_log" from "anon";

revoke references on table "public"."time_log" from "anon";

revoke select on table "public"."time_log" from "anon";

revoke trigger on table "public"."time_log" from "anon";

revoke truncate on table "public"."time_log" from "anon";

revoke update on table "public"."time_log" from "anon";

revoke delete on table "public"."time_log" from "authenticated";

revoke insert on table "public"."time_log" from "authenticated";

revoke references on table "public"."time_log" from "authenticated";

revoke select on table "public"."time_log" from "authenticated";

revoke trigger on table "public"."time_log" from "authenticated";

revoke truncate on table "public"."time_log" from "authenticated";

revoke update on table "public"."time_log" from "authenticated";

revoke delete on table "public"."time_log" from "service_role";

revoke insert on table "public"."time_log" from "service_role";

revoke references on table "public"."time_log" from "service_role";

revoke select on table "public"."time_log" from "service_role";

revoke trigger on table "public"."time_log" from "service_role";

revoke truncate on table "public"."time_log" from "service_role";

revoke update on table "public"."time_log" from "service_role";

alter table "public"."time_log" drop constraint "public_time_log_block_id_fkey";

alter table "public"."time_log" drop constraint "time_entry_id_key";

alter table "public"."time_log" drop constraint "time_entry_pkey";

drop index if exists "public"."time_entry_id_key";

drop index if exists "public"."time_entry_pkey";

drop table "public"."time_log";

create table "public"."logbook" (
    "id" bigint generated by default as identity not null,
    "start" timestamp with time zone not null,
    "end" timestamp with time zone not null,
    "block_id" bigint not null
);


alter table "public"."logbook" enable row level security;

CREATE UNIQUE INDEX time_entry_id_key ON public.logbook USING btree (id);

CREATE UNIQUE INDEX time_entry_pkey ON public.logbook USING btree (id);

alter table "public"."logbook" add constraint "time_entry_pkey" PRIMARY KEY using index "time_entry_pkey";

alter table "public"."logbook" add constraint "public_time_log_block_id_fkey" FOREIGN KEY (block_id) REFERENCES block(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."logbook" validate constraint "public_time_log_block_id_fkey";

alter table "public"."logbook" add constraint "time_entry_id_key" UNIQUE using index "time_entry_id_key";

grant delete on table "public"."logbook" to "anon";

grant insert on table "public"."logbook" to "anon";

grant references on table "public"."logbook" to "anon";

grant select on table "public"."logbook" to "anon";

grant trigger on table "public"."logbook" to "anon";

grant truncate on table "public"."logbook" to "anon";

grant update on table "public"."logbook" to "anon";

grant delete on table "public"."logbook" to "authenticated";

grant insert on table "public"."logbook" to "authenticated";

grant references on table "public"."logbook" to "authenticated";

grant select on table "public"."logbook" to "authenticated";

grant trigger on table "public"."logbook" to "authenticated";

grant truncate on table "public"."logbook" to "authenticated";

grant update on table "public"."logbook" to "authenticated";

grant delete on table "public"."logbook" to "service_role";

grant insert on table "public"."logbook" to "service_role";

grant references on table "public"."logbook" to "service_role";

grant select on table "public"."logbook" to "service_role";

grant trigger on table "public"."logbook" to "service_role";

grant truncate on table "public"."logbook" to "service_role";

grant update on table "public"."logbook" to "service_role";


