import { TimeFormat } from "./timeformat.slint";
import { ListView, ScrollView } from "std-widgets.slint";

enum TaskState {
    started,
    stopped
}

component TaskButton inherits Rectangle {
    in property <int> spent;
    in property <int> allot;
    in property <TaskState> state;
    callback clicked<=>touch.clicked;
    HorizontalLayout {
        spacing: 16px;
        Rectangle {
            width: 56px;
            height: 40px;
            background: touch.pressed ? #353535 : touch.has-hover ? #757575 : #959595;
            Text {
                font-size: 16px;
                text: state == TaskState.started ? "Stop" : "Start";
            }

            touch := TouchArea { }
        }

        TimeFormat {
            overflow: elide;
            visible: parent.width > 165px;
            vertical-alignment: TextVerticalAlignment.center;
            spent: spent;
            allot: allot;
            font-size: 10px;
        }
    }
}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
enum CheckBoxState {
    none,
    todo,
    doing,
    done
}

export struct InfoStruct {
    info: string,
    tabs: string,
    checkbox: CheckBoxState}

export struct TaskStruct {
    title: string,
    color: color,
    abbr: string,
    info: [InfoStruct],
    blocks: float,
    spent: float,
    allot: int,
    idx: [int],
    started: bool}

component CheckBox inherits Rectangle {
    in-out property <CheckBoxState> state;
    in property <brush> check-color;
    in property <brush> box-color;
    HorizontalLayout {
        Rectangle {
            border-color: box-color;
            border-radius: 2px;
            border-width: 1px;
            HorizontalLayout {
                padding: 2px;
                Image {
                    colorize: check-color;
                    source: state == CheckBoxState.doing ? @image-url("images/hourglass.svg") : @image-url("images/check.svg");
                    opacity: root.state == CheckBoxState.todo ? 0 : 1.0;
                }
            }
        }
    }
}

export component Task inherits Rectangle {
    in-out property <TaskStruct> task;
    property <duration> start-anim;
    property <bool> scroll_title: false;
    callback clicked<=>touch.clicked;
    callback button_clicked<=>button.clicked;
    border-radius: 4px;
    border-width: 0px;
    background: task.color;
    preferred-height: 160px;
    preferred-width: 60px * task.blocks;
    min-width: 60px;
    touch := TouchArea { }

    VerticalLayout {
        spacing: 8px;
        padding: 8px;
        alignment: stretch;
        title := Flickable {
            height: title_txt.height;
            viewport-width: title-txt.width;
            viewport-x: title-touch.pressed && title-txt.width >= title.width 
                ? clamp(((animation-tick() - start-anim) / -1ms) / (title.width / 2 / 1px), (title.width - title-txt.width) / 1px, 0) * 1px
                : 0px ;
            title-txt := Text {
                min-width: 64px;
                text: task.title;
                font-size: 24px;
                color: #000;
            }
            title-touch := TouchArea {
                pointer-event(pe) => {
                    if pe.kind == PointerEventKind.down {
                        start-anim = animation-tick();
                    }
                }
            }
        }

        infoview := Rectangle {
            border-radius: 4px;
            background: task.color.darker(0.1);
            HorizontalLayout {
                padding-top: 4px;
                padding-left: 4px;
                padding-right: 2px;
                ListView {
                    min-height: 16px;
                    for info in task.info: HorizontalLayout {
                        alignment: start;
                        Text {
                            text: info.tabs;
                        }

                        VerticalLayout {
                            alignment: start;
                            padding-right: 4px;
                            if info.checkbox != CheckBoxState.none:
                                    CheckBox {
                                height: 12px;
                                width: 12px;
                                state: info.checkbox;
                                check-color: black;
                                box-color: infoview.background.darker(0.6);
                            }
                        }

                        Text {
                            text: info.info;
                            wrap: word-wrap;
                        }
                    }
                }
            }
        }

        TimeFormat {
            height: self.width < 165px ? self.preferred-height : 0px;
            overflow: elide;
            spent: task.spent;
            allot: task.allot;
            font-size: 10px;
        }

        button := TaskButton {
            state: task.started ? TaskState.started : TaskState.stopped;
            spent: task.spent;
            allot: task.allot;
        }
    }
}
