import {TaskStruct} from "./task.slint";
import {TimeFormat} from "./timeformat.slint";

export component Info inherits Rectangle {
    in-out property <TaskStruct> task;
    callback clicked <=> touch.clicked;
    border-radius: 4px;
    border-width: 0px;
    background: task.color;
    preferred-width: 480px;
    preferred-height: 320px;
    min-width: 64px;
    min-height: 64px;
    txt := 
        Text {
            text: task.title;
            x: 16px;
            y: 16px;
            font-size: 24px;
            color: #000;
        }
    button := Rectangle {
        width: 56px;
        height: 40px;
        x: 8px;
        y: parent.y + parent.height - self.height - 24px;
        background: touch.pressed ? #353535 : touch.has-hover ? #757575 :  #959595;
        Text {
            font-size: 16px;
            text: "Stop";
        }
        touch := TouchArea { }
    }
    info := Text {
        text: task.info;
        x: txt.x;
        y: txt.y + txt.height + 8px;
    }
    timeText := TimeFormat {
        spent: task.spent;
        allot: task.allot;
        font-size: 10px;
        x: button.x;
        y: button.y - self.height - 8px;
    }
}
