import {TaskStruct} from "./task.slint";
import {TimeFormat} from "./timeformat.slint";
import {TaskButton} from "./taskbutton.slint";
import { ScrollView } from "std-widgets.slint";

export component Info inherits Rectangle {
    in-out property <TaskStruct> task;
    callback clicked <=> button.clicked;
    border-radius: 4px;
    border-width: 0px;
    background: task.color;
    info_background := Rectangle {
        border-radius: 4px;
        x: info.x - 2px;
        y: info.y - 2px;
        width: info.width + 2px;
        height: info.height + 2px;
        background: task.color.darker(0.1);
    }
        
    VerticalLayout {
        spacing: 8px;
        padding: 16px;
        txt := 
            Text {
                text: task.title;
                font-size: 24px;
                color: #000;
            }
        info := ScrollView {
            padding-bottom: 16px;
            viewport-height: inner.height;
            inner := Text {
                x: 0;
                y: 0;
                width: parent.width;
                text: task.info;
                wrap: word-wrap;
            }}
        button := TaskButton {
            state: stop;
            spent: task.spent;
            allot: task.allot;
        }
    }
}
