import { TimeFormat } from "./timeformat.slint";
import { TaskButton } from "./taskbutton.slint";

export struct TaskStruct {
    title: string,
    color: color,
    abbr: string,
    info: string,
    blocks: float,
    spent: int,
    allot: int,
    idx: [int]
}

export component Task inherits Rectangle {
    in-out property <TaskStruct> task;
    callback clicked <=> button.clicked;
    border-radius: 4px;
    border-width: 0px;
    background: task.color;
    preferred-height: 160px;
    preferred-width: 120px * task.blocks;
    VerticalLayout {
        padding: 8px;
        alignment: space-between;
        text := Text {
            text: task.abbr != task.title && task.blocks < 2 ? task.abbr: task.title;
            font-size: 24px;
            color: #000;
        }
        button := TaskButton {
            state: start;
            spent: task.spent;
            allot: task.allot;
        }
    }
}