import {TimeFormat} from "./timeformat.slint";

enum TaskState {
    start,
    stop
}

export component TaskButton inherits Rectangle {
    in property <int> spent;
    in property <int> allot;
    in property <TaskState> state;
    callback clicked <=> touch.clicked;
    HorizontalLayout {
        spacing: 16px;
        Rectangle {
            width: 56px;
            height: 40px;
            background: touch.pressed ? #353535 : touch.has-hover ? #757575 :  #959595;
            Text {
                font-size: 16px;
                text: state == TaskState.start ? "Start" : "Stop";
            }
            touch := TouchArea { }
        }
        
        timeText := TimeFormat {
            vertical-alignment: TextVerticalAlignment.center;
            spent: spent;
            allot: allot;
            font-size: 10px;
        }
    }
}